const SONGS = [
    { id: 1,  title: "Blinding Lights",       artist: "The Weeknd",         duration: 200, genre: "Pop",        gradient: "linear-gradient(135deg,#ff416c,#ff4b2b)" },
    { id: 2,  title: "Shape of You",           artist: "Ed Sheeran",         duration: 234, genre: "Pop",        gradient: "linear-gradient(135deg,#f7971e,#ffd200)" },
    { id: 3,  title: "Levitating",             artist: "Dua Lipa",           duration: 203, genre: "Pop",        gradient: "linear-gradient(135deg,#a18cd1,#fbc2eb)" },
    { id: 4,  title: "Stay",                   artist: "The Kid LAROI",      duration: 141, genre: "Hip-Hop",    gradient: "linear-gradient(135deg,#0f2027,#2c5364)" },
    { id: 5,  title: "Peaches",                artist: "Justin Bieber",      duration: 198, genre: "R&B",        gradient: "linear-gradient(135deg,#f9d423,#ff4e50)" },
    { id: 6,  title: "Good 4 U",               artist: "Olivia Rodrigo",     duration: 178, genre: "Pop Rock",   gradient: "linear-gradient(135deg,#ee0979,#ff6a00)" },
    { id: 7,  title: "Montero",                artist: "Lil Nas X",          duration: 137, genre: "Hip-Hop",    gradient: "linear-gradient(135deg,#4e54c8,#8f94fb)" },
    { id: 8,  title: "Save Your Tears",        artist: "The Weeknd",         duration: 215, genre: "Synth-pop",  gradient: "linear-gradient(135deg,#373b44,#4286f4)" },
    { id: 9,  title: "Watermelon Sugar",       artist: "Harry Styles",       duration: 174, genre: "Pop",        gradient: "linear-gradient(135deg,#f953c6,#b91d73)" },
    { id: 10, title: "Dynamite",               artist: "BTS",                duration: 199, genre: "Pop",        gradient: "linear-gradient(135deg,#f7971e,#ffd200)" },
    { id: 11, title: "drivers license",        artist: "Olivia Rodrigo",     duration: 242, genre: "Pop",        gradient: "linear-gradient(135deg,#1a1a2e,#4a90d9)" },
    { id: 12, title: "Butter",                 artist: "BTS",                duration: 164, genre: "Pop",        gradient: "linear-gradient(135deg,#f6d365,#fda085)" },
    { id: 13, title: "Industry Baby",          artist: "Lil Nas X",          duration: 212, genre: "Hip-Hop",    gradient: "linear-gradient(135deg,#8e2de2,#4a00e0)" },
    { id: 14, title: "Heat Waves",             artist: "Glass Animals",      duration: 238, genre: "Indie Pop",  gradient: "linear-gradient(135deg,#00b4db,#0083b0)" },
    { id: 15, title: "As It Was",              artist: "Harry Styles",       duration: 167, genre: "Pop",        gradient: "linear-gradient(135deg,#ff9a9e,#fad0c4)" },
    { id: 16, title: "Easy On Me",             artist: "Adele",              duration: 224, genre: "Soul",       gradient: "linear-gradient(135deg,#bdc3c7,#2c3e50)" },
    { id: 17, title: "Bad Habits",             artist: "Ed Sheeran",         duration: 231, genre: "Dance-pop",  gradient: "linear-gradient(135deg,#e96c5a,#f7c59f)" },
    { id: 18, title: "Shivers",                artist: "Ed Sheeran",         duration: 207, genre: "Pop",        gradient: "linear-gradient(135deg,#56ccf2,#2f80ed)" },
    { id: 19, title: "Happier Than Ever",      artist: "Billie Eilish",      duration: 295, genre: "Pop",        gradient: "linear-gradient(135deg,#11998e,#38ef7d)" },
    { id: 20, title: "Positions",              artist: "Ariana Grande",      duration: 172, genre: "R&B",        gradient: "linear-gradient(135deg,#c471ed,#f64f59)" },
    { id: 21, title: "Mood",                   artist: "24kGoldn",           duration: 140, genre: "Hip-Hop",    gradient: "linear-gradient(135deg,#f093fb,#f5576c)" },
    { id: 22, title: "Astronaut in the Ocean", artist: "Masked Wolf",        duration: 133, genre: "Hip-Hop",    gradient: "linear-gradient(135deg,#0f0c29,#302b63)" },
    { id: 23, title: "Beggin'",                artist: "Maneskin",           duration: 211, genre: "Rock",       gradient: "linear-gradient(135deg,#e52d27,#b31217)" },
    { id: 24, title: "Sunflower",              artist: "Post Malone",        duration: 158, genre: "Hip-Hop",    gradient: "linear-gradient(135deg,#f9d423,#ff4e50)" },
    { id: 25, title: "Circles",               artist: "Post Malone",        duration: 215, genre: "Pop",        gradient: "linear-gradient(135deg,#00b894,#55efc4)" },
    { id: 26, title: "Rockstar",               artist: "DaBaby",             duration: 181, genre: "Hip-Hop",    gradient: "linear-gradient(135deg,#1e3c72,#2a5298)" },
    { id: 27, title: "Memories",               artist: "Maroon 5",           duration: 189, genre: "Pop",        gradient: "linear-gradient(135deg,#a8c0ff,#3f2b96)" },
    { id: 28, title: "Midnight Rain",          artist: "Taylor Swift",       duration: 174, genre: "Pop",        gradient: "linear-gradient(135deg,#4b0082,#7b2ff7)" },
];
